### ISSUE TITLE
[feat] User Setting

### ISSUE THREAD

**Issue by 2dilution2** [2dilution2/Guitarchi-is-sanai#2]
## 📌 설명
> User Settin

## 🗒️ Todo
- [x] User 엔티티 생성
- [x] User Controller 생성
- [x] User Service 생성
- [x] User Require 생성
